Translation of the blog's home page
reactjs/ar.react.dev pull request #575
Opened 2024-07-21 05:33 UTC by khabzox

I have just translated the home page of the blog and I am still working on completing the translation of the entire blog

2024-07-21 07:02 UTC, AhmedBaset requested changes
Thanks for opening this

Mostly, it looks good. I proposed some changes, please have a look

2024-07-21 07:02 UTC, AhmedBaset commented on src/content/blog/index.md
> +### جميع ملاحظات الإصدار {/*all-release-notes*/}
```suggestion
### جميع ملاحظات الإصدارات {/*all-release-notes*/}
```

2024-07-21 07:02 UTC, AhmedBaset commented on src/content/blog/index.md
> +ليس كل إصدار ريأكت يستحق منشور مدونة خاص به، ولكن يمكنك العثور على سجل تغيير مفصل لكل إصدار في ملف [`CHANGELOG.md`](https://github.com/facebook/react/blob/main/CHANGELOG.md) في مستودع ريأكت، وكذلك في
```suggestion
ليس كل إصدار React يستحق منشور مدونة خاص به، ولكن يمكنك العثور على سجل تغيير مفصل لكل إصدار في ملف [`CHANGELOG.md`](https://github.com/facebook/react/blob/main/CHANGELOG.md) في مستودع React، وكذلك في صفحة [الإصدارات](https://github.com/facebook/react/releases).
```

2024-07-22 02:54 UTC, khabzox commented
I've made all the changes

[Preview](https://ar-react-dev-git-fork-khabzox-main-fbopensource.vercel.app/blog)

2024-07-22 03:25 UTC, AhmedBaset approved these changes
Thank you

2024-07-22 03:27 UTC, merged